version: 2

jobs:
  build:
    docker:
      - image: cimg/base:stable
    parallelism: 1
    branches:
      ignore:
        - master
        - second-edition-ja
    steps:
      - run:
          name: Print message and exit
          command: |
            echo "NOTICE: Skipping CI on this $CIRCLE_BRANCH branch."
